"""Added follower followed entity and changed tweet timestamp to created_at

Revision ID: acc40ba6639b
Revises: d53bdaf98669
Create Date: 2020-04-01 00:18:30.644747

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'acc40ba6639b'
down_revision = 'd53bdaf98669'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('followers',
    sa.Column('follower_id', sa.Integer(), nullable=True),
    sa.Column('followed_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['followed_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['follower_id'], ['user.id'], )
    )
    op.add_column('tweet', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.create_index(op.f('ix_tweet_created_at'), 'tweet', ['created_at'], unique=False)
    op.drop_index('ix_tweet_timestamp', table_name='tweet')
    op.drop_column('tweet', 'timestamp')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tweet', sa.Column('timestamp', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.create_index('ix_tweet_timestamp', 'tweet', ['timestamp'], unique=False)
    op.drop_index(op.f('ix_tweet_created_at'), table_name='tweet')
    op.drop_column('tweet', 'created_at')
    op.drop_table('followers')
    # ### end Alembic commands ###
